// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Crawler.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Contentfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contentfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280912421_Content-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
